// proto/speedpb/speed.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/speedpb/speed.proto

package speedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider
type Provider int32

const (
	// PROVIDER_UNSPECIFIED
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	// PROVIDER_SPEEDTEST_NET
	Provider_PROVIDER_SPEEDTEST_NET Provider = 1
	// PROVIDER_FAST_COM
	Provider_PROVIDER_FAST_COM Provider = 2
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_SPEEDTEST_NET",
		2: "PROVIDER_FAST_COM",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED":   0,
		"PROVIDER_SPEEDTEST_NET": 1,
		"PROVIDER_FAST_COM":      2,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_speedpb_speed_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_proto_speedpb_speed_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_proto_speedpb_speed_proto_rawDescGZIP(), []int{0}
}

// Options
type Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// provider
	Provider Provider `protobuf:"varint,2,opt,name=provider,proto3,enum=proto.speedpb.Provider" json:"provider,omitempty"`
}

func (x *Options) Reset() {
	*x = Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_speedpb_speed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_proto_speedpb_speed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_proto_speedpb_speed_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

// TestResult
type TestResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// speed
	Speed *Speed `protobuf:"bytes,2,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_speedpb_speed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_speedpb_speed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_proto_speedpb_speed_proto_rawDescGZIP(), []int{1}
}

func (x *TestResult) GetSpeed() *Speed {
	if x != nil {
		return x.Speed
	}
	return nil
}

// Speed
type Speed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ip
	Ip string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	// host
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// download_mbps in Mbps (float64)
	DownloadMbps float64 `protobuf:"fixed64,4,opt,name=download_mbps,json=downloadMbps,proto3" json:"download_mbps,omitempty"`
	// upload_mbps in Mbps (float64)
	UploadMbps float64 `protobuf:"fixed64,5,opt,name=upload_mbps,json=uploadMbps,proto3" json:"upload_mbps,omitempty"`
	// latency_ns in ns
	LatencyNs int64 `protobuf:"varint,6,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
}

func (x *Speed) Reset() {
	*x = Speed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_speedpb_speed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Speed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speed) ProtoMessage() {}

func (x *Speed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_speedpb_speed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speed.ProtoReflect.Descriptor instead.
func (*Speed) Descriptor() ([]byte, []int) {
	return file_proto_speedpb_speed_proto_rawDescGZIP(), []int{2}
}

func (x *Speed) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Speed) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Speed) GetDownloadMbps() float64 {
	if x != nil {
		return x.DownloadMbps
	}
	return 0
}

func (x *Speed) GetUploadMbps() float64 {
	if x != nil {
		return x.UploadMbps
	}
	return 0
}

func (x *Speed) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

var File_proto_speedpb_speed_proto protoreflect.FileDescriptor

var file_proto_speedpb_speed_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x70, 0x62, 0x2f,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x64, 0x70, 0x62, 0x22, 0x44, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02,
	0x22, 0x3e, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2a,
	0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x70,
	0x65, 0x65, 0x64, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02,
	0x22, 0x96, 0x01, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x62, 0x70, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d,
	0x62, 0x70, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x62,
	0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x62, 0x70, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f,
	0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x4e, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x2a, 0x57, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45,
	0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1a, 0x0a, 0x16, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x50, 0x45, 0x45,
	0x44, 0x54, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x45, 0x54, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50,
	0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x41, 0x53, 0x54, 0x5f, 0x43, 0x4f, 0x4d,
	0x10, 0x02, 0x32, 0x4e, 0x0a, 0x0c, 0x53, 0x70, 0x65, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x44, 0x55, 0x4c, 0x54, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x64, 0x70, 0x62, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x64, 0x75, 0x6c, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_speedpb_speed_proto_rawDescOnce sync.Once
	file_proto_speedpb_speed_proto_rawDescData = file_proto_speedpb_speed_proto_rawDesc
)

func file_proto_speedpb_speed_proto_rawDescGZIP() []byte {
	file_proto_speedpb_speed_proto_rawDescOnce.Do(func() {
		file_proto_speedpb_speed_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_speedpb_speed_proto_rawDescData)
	})
	return file_proto_speedpb_speed_proto_rawDescData
}

var file_proto_speedpb_speed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_speedpb_speed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_speedpb_speed_proto_goTypes = []interface{}{
	(Provider)(0),      // 0: proto.speedpb.Provider
	(*Options)(nil),    // 1: proto.speedpb.Options
	(*TestResult)(nil), // 2: proto.speedpb.TestResult
	(*Speed)(nil),      // 3: proto.speedpb.Speed
}
var file_proto_speedpb_speed_proto_depIdxs = []int32{
	0, // 0: proto.speedpb.Options.provider:type_name -> proto.speedpb.Provider
	3, // 1: proto.speedpb.TestResult.speed:type_name -> proto.speedpb.Speed
	1, // 2: proto.speedpb.SpeedService.QuickDULT:input_type -> proto.speedpb.Options
	2, // 3: proto.speedpb.SpeedService.QuickDULT:output_type -> proto.speedpb.TestResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_speedpb_speed_proto_init() }
func file_proto_speedpb_speed_proto_init() {
	if File_proto_speedpb_speed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_speedpb_speed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_speedpb_speed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_speedpb_speed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Speed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_speedpb_speed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_speedpb_speed_proto_goTypes,
		DependencyIndexes: file_proto_speedpb_speed_proto_depIdxs,
		EnumInfos:         file_proto_speedpb_speed_proto_enumTypes,
		MessageInfos:      file_proto_speedpb_speed_proto_msgTypes,
	}.Build()
	File_proto_speedpb_speed_proto = out.File
	file_proto_speedpb_speed_proto_rawDesc = nil
	file_proto_speedpb_speed_proto_goTypes = nil
	file_proto_speedpb_speed_proto_depIdxs = nil
}
